version: "3.8"

services:
  caddy:
    image: caddy:2.0.0-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  webservice:
    build:
      context: "."
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
